version: '3.3'
services:
    web:
        build: ./app
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        depends_on:
            - redis-container
        networks:
            - front
            - back

    redis-container:
        image: redis
        networks: 
            - back

networks: 
    front:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
    back:
